export const iconMap = {
  csharp: "devicon-csharp-plain",
  aspnet: "devicon-dot-net-plain",
  python: "devicon-python-plain",
  css: "devicon-css3-plain",
  sass: "devicon-sass-original",
  tailwindcss: "devicon-tailwindcss-original",
  html: "devicon-html5-plain",
  javascript: "devicon-javascript-plain",
  typescript: "devicon-typescript-plain",
  bash: "devicon-bash-plain",
  powershell: "devicon-powershell-plain",
  sql: "devicon-azuresqldatabase-plain",
  nodejs: "devicon-nodejs-plain",
  react: "devicon-react-original",
  nextjs: "devicon-nextjs-original-wordmark",
  jira: "devicon-jira-plain",
  devops: "devicon-azuredevops-plain",
  github: "devicon-github-original",
  git: "devicon-git-plain",
  django: "devicon-django-plain",
  discordjs: "devicon-discordjs-plain",
  webpack: "devicon-webpack-plain",
  vercel: "devicon-vercel-original",
  mongodb: "devicon-mongodb-plain",
  threejs: "devicon-threejs-original",
  vite: "devicon-vitejs-plain"
} as const;
