name: Deploy to GitHub Pages

on:
    push:
        branches:
            - main
    workflow_dispatch:

jobs:
    # Build job
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Install jq
              run: sudo apt-get install -y jq

            - name: Clone and build projects from JSON
              env:
                  CI: false
                  GITHUB_TOKEN: ${{ secrets.GH_PAT }}
              run: |
                  bash ./.github/scripts/clone_and_build.sh ./projects.json

            # Delete non-folder files in root dir
            - name: Move index
              run: |
                  find . -maxdepth 1 -type f -exec rm {} \;
                    shopt -s extglob
                  mv ./index/* ./
                  rm -rf index

            - name: Setup Pages
              id: pages
              uses: actions/configure-pages@v3

            - name: Build with Jekyll
              uses: actions/jekyll-build-pages@v1
              with:
                  source: ./
                  destination: ./_site

            - name: Upload artifact
              uses: actions/upload-pages-artifact@v1

    # Deployment job
    deploy:
        environment:
            name: github-pages
            url: $
        permissions:
            contents: read
            pages: write
            id-token: write
        runs-on: ubuntu-latest
        needs: build
        steps:
            - name: Deploy to GitHub Pages
              id: deployment
              uses: actions/deploy-pages@v2
